//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EventService
    {
        public int EventServicesId { get; set; }
        [Display(Name = "Clint"),]
        public int ClientId { get; set; }
        [Display(Name = "Event"),]
        public int EventId { get; set; }
        [Display(Name = "Service Name"), Required]
        public string ServiceName { get; set; }
        [Display(Name = "Vendor Name"), Required]
        public string VendorName { get; set; }
        public Nullable<decimal> Cost { get; set; }

        public virtual Client Client { get; set; }
        public virtual Event Event { get; set; }
    }
}
